### PR TITLE
Add  support for systemd

### PR DESCRIPTION
**Pull request by junghans**
These patches have been used in Gentoo Linux for a while.

### CODE REVIEW

**Comment by jasontibbitts** [comment]
As the original author of those patches (they came from Fedora) let me know if explanation is needed.

Also, the service file can be altered to remove the ExecStartPre= and pass --unlock on the command line.  If --foreground didn't disable logging, the Type= and PIDFile: lines could be removed as well.

**Comment by junghans** [comment]
Yeah, it seems your version of `denyhosts.service` is cleaner.

**Comment by jasontibbitts** [comment]
Well, it would be, but for some reason --unlock and --daemon don't work together.  I've no idea why, but ugh.

**Comment by junghans** [comment]
Ok, reverted to what is working on Gentoo!

**Comment by jasontibbitts** [comment]
Actually, you know what?  --unlock is mentioned in the help and in the manpage, but it's not actually implemented in the code at all.  (!)  I'll work on that tonight.

**Comment by jasontibbitts** [comment]
With the current denyhosts sources (so --unlock works and --foreground still logs) I'm able to use a very minimal unit file, where the [Service] section is just:

ExecStart=/usr/bin/denyhosts.py --foreground --unlock --config=/etc/denyhosts.conf

**Pull request merged**
