### PR TITLE
Support other methods for sending report e-mail

### PR DESCRIPTION
**Pull request by mblythe86**
As far as I know, there aren't any open SMTP relays anymore.  Even ISPs don't seem to offer them.  So, the SMTP method of sending e-mail is pretty limited.

On my particular system, I've configured postfix to use gmail as an SMTP relay.  This means that DenyHosts doesn't need to know the SMTP details, it can just use existing utilities to send mail.  These include the "mail" and "sendmail" commands.  Also, for completeness, I've added a method to just print the message to stdout.  Since DenyHosts can be run as a cron job, we can leave it up to cron to e-mail what we print to stdout to the appropriate mailbox.

### CODE REVIEW

**Comment by ZerooCool** [comment]
With gmail, free, domaine and mail from OVH, hotmail, we can use the SMTP accound for send mail.

I read, Denyhosts can't use SSL port 465 for SMTP.
I learn, stunnel can be used for secure SMTP port 25.

https://wiki.visionduweb.fr/index.php?title=Sommaire_S%C3%A9curit%C3%A9#Les_mails_ne_sont_pas_envoy.C3.A9s

It's a good way if SMTP 465 can be used.
It's better if this work directly with denyhost.

I my situation, i want use Debian and Exim4, send to root@localhost or user@localhost, or, root or user only, and, exim4 need send all mail.

https://wiki.visionduweb.fr/index.php?title=Installer_un_serveur_mail#Exim

Actually, i use Fail2ban and Denyhost, and, i have the mail from fail2ban but i never have the mail from Denyhosts.

**Comment by ZerooCool** [comment]
With my server in production.

For test if the mail was send, i found that :

To get DenyHosts to send you a test email.

Login to your Linux system containing the sshd server and switch to root user.
Append the following line to the file /etc/hosts.deny - sshd: 127.0.0.1
Save the file
Attempt to connect to the local sshd server: - $ ssh localhost (if you are connecting on a port other than 22, use the -p switch)
You should receive the following error message: - ssh_exchange_identification: Connection closed by remote host
You should also have been sent an email from DenyHosts [Nobody@yourserver]
Remember to remove the line you added to the file /etc/hosts.deny - save the file.

Source : https://superuser.com/questions/363974/how-to-test-if-the-denyhosts-can-send-me-an-email

I test and i obtain this : 

```
ssh localhost
kex_exchange_identification: read: Connection reset by peer
```

I suppose it's the same probleme, SSH with public key conf.
In the conf SSH, i accept only one user, my authorized user. ( myusersudoers )

From auth.log : 
```
sshd[8743]: refused connect from 127.0.0.1 (127.0.0.1)
sshd[8823]: refused connect from 127.0.0.1 (127.0.0.1)
```

But, i don't have any mail.

Need test with the test serveur with SSHD not loocked by public key.

From my serveur in production :
```
ssh -v localhost
OpenSSH_8.0p1 Debian-3, OpenSSL 1.1.1d  10 Sep 2019
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to localhost [127.0.0.1] port 22.
debug1: Connection established.
debug1: identity file /home/USER/.ssh/id_rsa type -1
debug1: identity file /home/USER/.ssh/id_rsa-cert type -1
debug1: identity file /home/USER/.ssh/id_dsa type -1
debug1: identity file /home/USER/.ssh/id_dsa-cert type -1
debug1: identity file /home/USER/.ssh/id_ecdsa type -1 
debug1: identity file /home/USER/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/USER/.ssh/id_ed25519 type -1
debug1: identity file /home/USER/.ssh/id_ed25519-cert type -1
debug1: identity file /home/USER/.ssh/id_xmss type -1
debug1: identity file /home/USER/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.0p1 Debian-3
kex_exchange_identification: read: Connection reset by peer
```

**Comment by josev814** [comment]
> I read, Denyhosts can't use SSL port 465 for SMTP.
> I learn, stunnel can be used for secure SMTP port 25.

As of pr #100 which was merged in, it's possible to use SSL for sending e-mails now

**Comment by ZerooCool** [comment]
I flew over the shit and I read sendmail, I think I understand that before, the system was different and probably not functional, or, not really adapted.

It remains to define a method for testing the sending of emails.

I do not know if the method proposed above works. (Still works / someday working)

**Pull request merged**
